module.exports = {
	"Travelling As a Student": "http://www.exchangebuddy.com/wp-content/uploads/2016/10/o1.png",
	"Why You Should Go For Student Exchange Programme (SEP)": "http://www.exchangebuddy.com/wp-content/uploads/2016/07/WHY-STUDENT-EXCHANGE-PROGRAMME-SEP_.png",
	"How to Apply for NUS Student Exchange Programme in 6 Easy Steps": "http://www.exchangebuddy.com/wp-content/uploads/2016/07/SEP-Application.png",
	"Your ULTIMATE GUIDE To An Exchange In Singapore": "http://www.exchangebuddy.com/wp-content/uploads/2016/10/Exchange-In-Singapore.jpg",
	"Benefits of Culture Shock During Student Exchange": "http://www.exchangebuddy.com/wp-content/uploads/2016/10/Benefits-of-culture-shock.png",
	"8 Tips For The Best Hostel Experience": "http://www.exchangebuddy.com/wp-content/uploads/2016/09/8Tips.png",
	"WHU Otto Beisheim Graduate School of Management - The Hidden Gem": "http://www.exchangebuddy.com/wp-content/uploads/2016/07/IMG_3607.jpg",
	"8 Simple Tips For Backpacking In Europe": "http://www.exchangebuddy.com/wp-content/uploads/2016/07/backpacking-in-europe2.jpg",
	"Exchange Program in Poland": "http://www.exchangebuddy.com/wp-content/uploads/2016/08/The-Warsaw-Experience.jpg",
	"National Day Special: What Singaporean Abroad Miss the Most.": "http://www.exchangebuddy.com/wp-content/uploads/2016/08/What-Singaporeans-Abroad-Miss-the-Most-7.jpg",
	"Warsaw City Guide": "http://www.exchangebuddy.com/wp-content/uploads/2016/08/Warsaw-City-Guide.jpg",
	"Exchange Student Bank Comparison":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/Bank-Comparison.jpg",
	"Best Means to Spend Money Overseas": "http://www.exchangebuddy.com/wp-content/uploads/2016/07/Card-withdrawal-or-cash-.jpg",
	"Preparing Your Credit and Debit Cards":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/Debit-VS-Credit-1.jpg",
	"Leprechaun Chasing":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/IMG_4854.jpg",
	"12 Things You Must Pack In Your Luggage Before Exchange":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/12-things-to-bring.jpg",
	"Getting Your International Driving Permit (IDP)":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/Unknown-4-e1469151507457.jpg",
	"Pre-departure Guide To York University, CANADA":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/shulich-6_sm-e1448307887852.jpg",
	"3 days in Copenhagen":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/Nyhavn-Harbor.jpg",
	"7 Must-Know Money-Saving Tips When on Exchange in Australia":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/11807231_10152905675727003_3791406532288145674_o.jpg",
	"Pre-departure Guide to University of Washington":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/IMG_8834-e1468259297725.jpg",
	"South Korea: Traveling out of Seoul":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/namsan.jpg",
	"Maastricht: Myths and Truths":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/DSC00400.jpg",
	"Manchester: The Guide to the Gig Life":"http://www.exchangebuddy.com/wp-content/uploads/2016/07/Screen-Shot-2016-07-10-at-1.40.45-PM.png",
	"Learning How to Speak American":"http://www.exchangebuddy.com/wp-content/uploads/2016/06/QSC_0247.jpg",
	"4 Reasons Why You Should NOT Visit Venice":"http://www.exchangebuddy.com/wp-content/uploads/2016/06/IMG_6754.jpg",
	"How to plan a short weekend getaway in New York?":"http://www.exchangebuddy.com/wp-content/uploads/2016/06/IMG_3141.jpg",
	"Enter Manchester":"http://www.exchangebuddy.com/wp-content/uploads/2016/06/File_000-1.jpeg",
	"SEP in South KoreaSEP in South Korea":"http://www.exchangebuddy.com/wp-content/uploads/2016/06/exchangebuddy.jpg",
	"Seven Days into Exchange Country (Warsaw, Poland)":"http://www.exchangebuddy.com/wp-content/uploads/2016/05/to-be-deleted-2.jpg",
	"10 essential steps to a successful exchange application":"http://www.exchangebuddy.com/wp-content/uploads/2016/05/to-be-deleted.png",
	"100 Euro Budget Travels: 3D2N in Budapest, Hungary":"http://www.exchangebuddy.com/wp-content/uploads/2016/05/delete.jpg",
	"The College Student's Multi-Meal Recipes for under €20":"http://www.exchangebuddy.com/wp-content/uploads/2016/05/IMG_3839-6.jpg",
	"Day Trip to Zaanse Schans":"http://www.exchangebuddy.com/wp-content/uploads/2016/05/IMG_5887-2.jpg",
	"Flowers of Keukenhof (2016)":"http://www.exchangebuddy.com/wp-content/uploads/2016/05/IMG_6289-1.jpg",
	"My First Couchsurf Experiences in Belgium – Geel and Brussels":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_3148.jpg",
	"Day trip in Brussels and Bruges (Belgium)":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_3667.jpg",
	"Day trip in Antwerp and Ghent (Belgium)":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_3100.jpg",
	"8 Places to visit in Belgium for Waffles, Icecream, and Coffee":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_3291.jpg",
	"Battle of the Belgian Fries in 5 Cities":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_3155.jpg",
	"The guide to Iceland you will need":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/MEL_0452.jpg",
	"Warsaw walkabout and Baltic beauty":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/DSC_0007_37.jpg",
	"Albert Cuyp Market - Fresh Stroopwaffles and more!":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/img_1594.jpg",
	"Fulfilling your Asian needs in Chinatown":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_2723.jpg",
	"5 Icecream Parlours to visit in Amsterdam5 Icecream Parlours to visit in Amsterdam":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/img_2764.jpg",
	"The Museum District of Amsterdam":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_1645-1.jpg",
	"5 Cafes to visit in Jordaan, Amsterdam":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_5204.jpg",
	"Education in the Netherlands":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_0830-1.jpg",
	"Welcome to Amsterdam! (and some bicycle tips)":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/IMG_5268_69_70_tonemapped.jpg",
	"Pre-departure : 8 things to prepare before your student exchange to Poland":"http://www.exchangebuddy.com/wp-content/uploads/2016/04/27WARSAW1-jumbo.jpg",
	"Muses: Pre-Departure for Bocconi":"http://www.exchangebuddy.com/wp-content/uploads/2016/03/IMG_9710.jpg",
	"Predepature: Canada":"http://www.exchangebuddy.com/wp-content/uploads/2016/03/2016-02-04-16.38.46.jpg",
	"Road Tripping in Ontario, Canada":"http://www.exchangebuddy.com/wp-content/uploads/2016/03/IMG-20160319-WA0033.jpg",
	"D-Day to Germany!":"http://www.exchangebuddy.com/wp-content/uploads/2016/03/IMG_20160310_165324655.jpg",
	"SEP in Canada":"http://www.exchangebuddy.com/wp-content/uploads/2016/03/2016-03-06-10.41.28.jpg",
	"The Biking City: Copenhagen":"http://www.exchangebuddy.com/wp-content/uploads/2016/03/bikes.jpg",
	"2016 European City of Culture - Wroclaw":"http://www.exchangebuddy.com/wp-content/uploads/2016/03/DSC_0365_1.jpg",
	"Travel time in Poland- Local lights and Krakow Sights":"http://www.exchangebuddy.com/wp-content/uploads/2016/03/DSC_0293.jpg",
	"Classes, Castles and Chopin":"http://www.exchangebuddy.com/wp-content/uploads/2016/02/DSC_0003.jpg",
	"Week one in Warsaw done":"http://www.exchangebuddy.com/wp-content/uploads/2016/02/DSC_0101_3.jpg",
	"Things to do during a stopover at Oslo, Norway":"http://www.exchangebuddy.com/wp-content/uploads/2016/02/img_7201-1.jpeg",
	"My First Impressions In Warsaw":"http://www.exchangebuddy.com/wp-content/uploads/2016/02/DSC_0071_6-e1464275237353.jpg",
	"Introductions and Hi's":"http://www.exchangebuddy.com/wp-content/uploads/2016/02/Nik-Chan.jpg",

}
